Move system stats to backend
chaiNNer-org/chaiNNer pull request #1948
Opened 2023-07-18 04:00 UTC by joeyballentine

Probably fixes #1105.

Moves the system information collection to a backend route which the fronted polls using react-query. Requires psutil as a new dependency, which compared to what I was using for system stats with nodejs, is _so_ much better lol.

2023-07-18 14:54 UTC, RunDevelopment requested changes
See #1951 for more.

2023-07-18 14:54 UTC, RunDevelopment commented on backend/src/server.py
> +async def system_stats(_request: Request):
Why did you call the end point "system stats"? Wouldn't "system usage" be better? 

When I first read the title of this PR, I thought that you moved the system info collection for error logs into the backend.

2023-07-19 02:03 UTC, joeyballentine commented
lol i clicked "cancel review" and it posted the wip review I was making earlier from my phone. thanks github

2023-07-19 19:01 UTC, RunDevelopment approved these changes

2023-07-19 20:20 UTC, merged